export enum bankOptions {
  BANCODOBRASIL_V2 = "BANCODOBRASIL_V2",
  SANTADANDER = "SANTANDER",
  BANRISUL = "BANRISUL",
  INTER = "INTER",
  CAIXA = "CAIXA",
  ITAU_V2 = "ITAU_V2",
  ITAU_FRANCESA = "ITAU_FRANCESA",
  SICREDI_V2 = "SICREDI_V2",
  SICREDI_V3 = "SICREDI_V3",
  SICOOB_V2 = "SICOOB_V2",
}
